"""
Django settings for mtn project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z=wohoh*zvwgk)c!y0gd%^+)!8bp_@=ipjb(y&1$2cg$-xtoal'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'momo',
    'background_task'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mtn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mtn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #'HOST': '127.0.0.1',
        #'PORT': 3306,
        #'USER': 'root',
        #'PASSWORD': 'mysql',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MOMO_URL='https://ericssonbasicapi2.azure-api.net'
API_USERID="bed7dfb2-4048-45de-8ddf-e9841168f13f"
API_KEY='9c46f25e11dc418585ef923cac696bfc'

DISBURSE_KEY='030fd379f3094d73bedec6150c078674'
DISBURSE_KEY2='edc040ff056046c2816e51019d165efc'

COLLECT_KEY='4751fc363a4444d99db749c4ff0ef6f6'
COLLECT_KEY2='6650d7e9ed32470cb876da73be7769fc'
CURRENCY="EUR"

ACCESS_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJSMjU2In0.eyJjbGllbnRJZCI6ImJlZDdkZmIyLTQwNDgtNDVkZS04ZGRmLWU5ODQxMTY4ZjEzZiIsImV4cGlyZXMiOiIyMDE5LTA4LTEzVDE2OjEyOjQ5LjUzOCIsInNlc3Npb25JZCI6IjNiMDE1NDA4LTkxZTgtNDczOC1iMTljLTE2YWExOWNmNTkwNSJ9.ar125n3UEeQBAdAn3PddHFkLIbuSOhwpF12ZOgIRpFDqsNh7R333ryPPiQenqE8F1ks6Om_Tp_wwHH09QADstRwu8O5B1u2E4O4_JgJES8I9ZN2dQiAxGEM1KmB5UbyuvKJZG_iyhNgeVdz6rtjhAPmFQvAlkYMhZ5Js1fP0v1L3s3GdJRyCmlfaVjsBNcaK_rap4rKOxOI3O1tNnuG_BNWv1BTFuaVoR46ZMROoVMWw9S3_thTZqgtIkfwbdMYyT62CdHPiiMknKvJmJHJJ8ZVOivw85vBNq8nPb0nat4tgXEPKW3RXUjhY-DkQP7QzGdXjg-ixa7LTyVNRNgYQ8g"

#background transaction polling settings
MAX_ATTEMPTS=5