# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('54b106cc-d366-4921-b714-4dd5f23332f6'), editable=False, primary_key=True, serialize=False)),
                ('msisdn', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=16)),
                ('momo_referene', models.CharField(blank=True, max_length=255, null=True)),
                ('momo_status', models.CharField(default='PENDING', max_length=16)),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(max_length=5)),
            ],
        ),
    ]
