# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momorequest',
            old_name='error_code',
            new_name='status_code',
        ),
        migrations.AlterField(
            model_name='momorequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fb91a75-49fa-4f15-a2ed-8063ad28c7df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
