# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0002_auto_20190813_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momorequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16c20f4e-1082-4980-95d1-9c8035540eef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='momorequest',
            name='status_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='momorequest',
            name='type',
            field=models.CharField(default='COLLECT', max_length=16),
        ),
    ]
