# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0003_auto_20190813_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momorequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34f716af-b8e4-41c0-9e6d-ea8d1683a4d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
